takenet/blip-ds-flutter

lib/src/widgets/utils/ds_header.widget.dart
Inclusion of Elevation and onTap parameters in appBar.
=> AppBar changes

lib/src/widgets/chat/ds_image_message_bubble.widget.dart, sample/android/app/build.gradle, sample/ios/Podfile, sample/ios/Podfile.lock, sample/ios/Runner.xcodeproj/project.pbxproj, sample/macos/Flutter/GeneratedPluginRegistrant.swift, sample/pubspec.lock
- Fix image loading in DSImageMessageBubble
- Update sample's deployment target version of iOS from 11.0 to 12.1
=> [Bugfix] - Image Loading

CHANGELOG.md, lib/src/widgets/chat/ds_image_message_bubble.widget.dart, pubspec.yaml, sample/android/app/build.gradle, sample/ios/Podfile, sample/ios/Podfile.lock, sample/ios/Runner.xcodeproj/project.pbxproj, sample/macos/Flutter/GeneratedPluginRegistrant.swift, sample/pubspec.lock
* [DSImageMessageBubble] Fix image loading container
* [Sample] Update deployment target version of iOS from 11.0 to 12.1
=> [Release] - 0.0.26

lib/src/controllers/ds_video_player.controller.dart, lib/src/services/ds_dialog.service.dart, lib/src/services/ds_toast.service.dart, lib/src/widgets/utils/ds_group_card.widget.dart, sample/lib/widgets/showcase/sample_dialog.showcase.dart, sample/pubspec.lock
This feature aims to add a scroll controller property in DSGroupCard, so the scroll behavior could be controlled outside of this widget. Read the full changelist below:
- Improve readability in DSDialogService
- Fix DSToast icon size from undefined to 24.0
- Add scroll controller prop in DSGroupSize
=> [Feature] 395856 - Reconnect Error

CHANGELOG.md, lib/blip_ds.dart, lib/src/controllers/ds_video_player.controller.dart, lib/src/services/ds_dialog.service.dart, lib/src/services/ds_toast.service.dart, lib/src/themes/colors/ds_colors.theme.dart, lib/src/themes/colors/ds_linear_gradient.theme.dart, lib/src/widgets/utils/ds_group_card.widget.dart, pubspec.yaml, sample/lib/widgets/showcase/sample_dialog.showcase.dart, sample/pubspec.lock
* [DSDialogService] Improve readability
* [DSToast] Fix icon size from undefined to 24.0
* [DSGroupCard] Add scroll controller property
* [DSLinearGradient] Add linear gradient widget
=> [Release] 0.0.27

lib/src/widgets/chat/video/ds_video_player.widget.dart, lib/src/widgets/utils/ds_header.widget.dart
New adjust DSHeader to video and imagem preview page accessed from chat page.
=> Feature adjust ds header

lib/src/widgets/utils/ds_progress_bar.widget.dart
Created animation in progress bar
=> Created animation

CHANGELOG.md, lib/src/controllers/chat/ds_video_message_bubble.controller.dart, lib/src/widgets/chat/audio/ds_audio_player.widget.dart, pubspec.yaml, sample/macos/Flutter/GeneratedPluginRegistrant.swift, sample/pubspec.lock
This bugfix aims to fix audio player on iOS when reproducing .ogg files.
=> [Bugfix] #433215 - FFMPEG package

.github/workflows/release.yml, .github/workflows/tests.yml, CHANGELOG.md, lib/src/controllers/chat/ds_video_message_bubble.controller.dart, lib/src/widgets/chat/audio/ds_audio_player.widget.dart, pubspec.yaml, sample/macos/Flutter/GeneratedPluginRegistrant.swift, sample/pubspec.lock
* [DSAudioPlayer] Fixed audio player on iOS when reproducing .ogg files.
=> [Release] 0.0.45

CHANGELOG.md, lib/blip_ds.dart, lib/src/services/ds_bottom_sheet.service.dart, lib/src/themes/texts/styles/ds_body_text_style.theme.dart, lib/src/themes/texts/styles/ds_button_text_style.theme.dart, lib/src/themes/texts/styles/ds_caption_small_text_style.theme.dart, lib/src/themes/texts/styles/ds_caption_text_style.theme.dart, lib/src/themes/texts/styles/ds_headline_large_text_style.theme.dart, lib/src/themes/texts/styles/ds_headline_small_text_style.theme.dart, lib/src/themes/texts/styles/ds_text_style.theme.dart, lib/src/widgets/fields/ds_select_input.widget.dart, lib/src/widgets/texts/ds_body_text.widget.dart, lib/src/widgets/texts/ds_button_text.widget.dart, lib/src/widgets/texts/ds_caption_small_text.widget.dart, lib/src/widgets/texts/ds_caption_text.widget.dart, lib/src/widgets/texts/ds_headline_large_text.widget.dart, lib/src/widgets/texts/ds_headline_small_text.widget.dart, lib/src/widgets/texts/ds_text.widget.dart, pubspec.yaml
* Add font style prop to typography widgets.
* [DSBottomsheetService] Improve grabber visibility.
* [DSHeadlineLargeText] Fix default font weight.
* [DSSelectInput] Add select field (LOV) widget.
=> [Release] 0.0.49

lib/src/widgets/fields/ds_input_phone.widget.dart
This feature aims to improve const declaration in DSInputPhone widget.
=> [Feature] 456849 - Improve const declaration in DSInputPhone

CHANGELOG.md, lib/src/widgets/tags/ds_input_chip.widget.dart, pubspec.yaml, sample/pubspec.lock
- [DSInputChip] Fix text padding
=> [Release] 0.0.58

CHANGELOG.md, lib/src/widgets/texts/ds_body_text.widget.dart, lib/src/widgets/texts/ds_button_text.widget.dart, lib/src/widgets/texts/ds_caption_small_text.widget.dart, lib/src/widgets/texts/ds_caption_text.widget.dart, lib/src/widgets/texts/ds_headline_large_text.widget.dart, lib/src/widgets/texts/ds_headline_small_text.widget.dart
This bugfix aims to fix the line height for all DSTexts subtypes.
=> [Bugfix] Typography Line Height

lib/src/services/ds_auth.service.dart
This feature aims to improve DSAuthService usability and readability to better expose what their methods really do.
=> [Feature] 495046 - Improve DSAuthService Usability

lib/src/controllers/chat/ds_image_message_bubble.controller.dart, lib/src/widgets/chat/ds_image_message_bubble.widget.dart, lib/src/widgets/utils/ds_expanded_image.widget.dart
Add few more HTTP headers for media authentication.
=> [Bugfix] 495046 - Media HTTP Headers

lib/src/utils/ds_animate.util.dart
This avoids error when the listView is empty
=> Fix when listview is empty

CHANGELOG.md, lib/src/widgets/utils/ds_group_card.widget.dart, pubspec.yaml
- [DSColors] Fixed system color;
- [DSAnimate] Added check to see if scrollController has clients.
=> [Release] 0.0.72

lib/src/widgets/utils/ds_chip.widget.dart
[set shape to circle when text is null](https://github.com/takenet/blip-ds-flutter/commit/7a11e3d6e2c707ad461b9cf8c78315db619b02f2)
=> Set shape to circle when text is null

lib/src/themes/colors/ds_colors.theme.dart, lib/src/widgets/animations/ds_spinner_loading.widget.dart
Changed to new color and set as default
=> feat: change the spinner color

CHANGELOG.md, lib/src/widgets/buttons/ds_send_button.widget.dart, pubspec.yaml, sample/pubspec.lock
- [FFMPEG] Downgraded ffmpeg dependency version from 6.0.2 to 5.1.0
=> [Release] 0.0.79

CHANGELOG.md, lib/src/controllers/chat/ds_video_message_bubble.controller.dart, lib/src/widgets/chat/audio/ds_audio_player.widget.dart, pubspec.yaml, sample/pubspec.lock
This PR aims to fix all FFMPEG commmands that has input/output arguments by wrapping them with double quotes.
=> [Bugfix] FFMPEG Commands

CHANGELOG.md, lib/src/controllers/chat/ds_video_message_bubble.controller.dart, lib/src/widgets/buttons/ds_send_button.widget.dart, lib/src/widgets/chat/audio/ds_audio_player.widget.dart, pubspec.yaml, sample/pubspec.lock
- [FFMPEG] Upgraded ffmpeg dependency version from 5.1.0 to 6.0.3
- [FFMPEG] Added double quotes in commands
=> [Release] 0.0.80

CHANGELOG.md, pubspec.yaml, sample/pubspec.lock
* [FFMPEG] Downgraded ffmpeg dependency version from 6.0.2 to 5.1.0
=> Release v0.0.81

CHANGELOG.md, lib/blip_ds.dart, lib/src/widgets/chat/ds_image_message_bubble.widget.dart, lib/src/widgets/chat/video/ds_video_message_bubble.widget.dart, lib/src/widgets/fields/ds_search_input.widget.dart, lib/src/widgets/radio/ds_radio_tile.widget.dart, lib/src/widgets/utils/ds_circular_progress.widget.dart, pubspec.yaml, sample/pubspec.lock
- [DSCircularProgress] Added widget to build circular progress indicator.
- [DSSearchInput] Added ```enabled``` property.
=> [Release] 0.0.87

CHANGELOG.md, lib/src/widgets/utils/ds_circular_progress.widget.dart, lib/src/widgets/utils/ds_expanded_image.widget.dart, pubspec.yaml
- [DSExpandedImage] Centered the circular progress loading.
=> [Release] 0.0.94

CHANGELOG.md, lib/blip_ds.dart, lib/src/themes/texts/styles/ds_headline_extra_large_text_style.theme.dart, lib/src/widgets/texts/ds_headline_extra_large_text.widget.dart, lib/src/widgets/utils/ds_header.widget.dart, lib/src/widgets/utils/ds_user_avatar.widget.dart, pubspec.yaml, sample/lib/main.dart, sample/lib/widgets/showcase/sample_text_style.showcase.dart, sample/lib/widgets/showcase/sample_user_avatar.showcas.dart
- [DSHeadlineExtraLargeTextStyle] Created text style primarily used by extra large titles.
- [DSHeadlineExtraLargeText] Created text that uses ```DSHeadlineExtraLargeTextStyle``` as style.
- [DSUserAvatar] Added ```textStyle``` property to allow customizing the style of font used by name initials.
=> [Release] 0.0.96

lib/src/widgets/utils/ds_expanded_image.widget.dart, sample/lib/widgets/showcase/sample_ticket_message.showcase.dart
fix layout issue when expand the image
before:
after:
=> fix: pinch_zoom layout fix

lib/src/widgets/chat/ds_url_preview.widget.dart
This PR aims to make the URL Preview bubble in the app to show an InkWell effect upon touch, for better usability.
=> [Feature] #645829 - URL preview InkWell response

CHANGELOG.md, lib/src/widgets/chat/ds_location_message_bubble.widget.dart, pubspec.yaml, sample/ios/Podfile.lock, sample/pubspec.lock
- [DSLocationMessageBubble] Added app selection when touching the map preview.
=> [Release] 0.1.2

CHANGELOG.md, lib/blip_ds.dart, lib/src/models/interactive_message/ds_interactive_message_action.model.dart, lib/src/models/interactive_message/ds_interactive_message_parameters.model.dart, lib/src/widgets/chat/ds_application_json_message_bubble.widget.dart, lib/src/widgets/chat/ds_interactive_voice_call_message_bubble.widget.dart, pubspec.yaml, sample/pubspec.lock
- [DSInteractiveVoiceCallMessageBubble] Added new bubble to render the request call message.
=> [Release] 0.1.4

lib/blip_ds.dart, lib/src/themes/colors/ds_colors.theme.dart, lib/src/themes/colors/ds_dark_colors.theme.dart
This PR aims to implement new colors to the app, which consists in a new file labeled DSDarkColors.
=> [Feature] #670767 - Call Page/Widget Layout

CHANGELOG.md, lib/src/widgets/chat/calls/ds_end_calls_message_bubble.widget.dart, pubspec.yaml
This PR aims to remove load recording state when session doesn't have available recording.
=> [Bugfix] #707375 - Remove Load Recording State

CHANGELOG.md, lib/src/widgets/chat/calls/ds_end_calls_message_bubble.widget.dart, lib/src/widgets/chat/ds_message_bubble.widget.dart, lib/src/widgets/chat/ds_survey_message_bubble.widget.dart, pubspec.yaml, sample/lib/widgets/showcase/sample_message_bubble.showcase.dart, sample/pubspec.lock
- [DSEndCallsMessageBubble] Fixed layout when used by small screens.
=> [Release] 0.2.0

CHANGELOG.md, lib/blip_ds.dart, lib/src/services/ds_security.service.dart, lib/src/widgets/texts/ds_text.widget.dart, pubspec.yaml, sample/pubspec.lock
[DSSecurityService] Add service to manage security features.
=> [Feature] #721161 - Improve Security

lib/src/models/ds_media_link.model.dart
This PR aims to add Sticker media support.
=> [Feature] #802874 - Sticker Support

CHANGELOG.md, lib/src/models/ds_reply_content.model.dart, lib/src/utils/ds_message_content_type.util.dart, lib/src/widgets/utils/ds_card.widget.dart, pubspec.yaml, sample/pubspec.lock
- Added support for Reactions.
=> [Release] 0.3.5

CHANGELOG.md, lib/src/widgets/utils/ds_group_card.widget.dart, pubspec.yaml
- [DSGroupCard] Added dark color to scroll button.
=> [Release] 0.3.7
